//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popryzhenok
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PopryzhenokEntities : DbContext
    {
        public PopryzhenokEntities()
            : base("name=PopryzhenokEntities")
        {
        }
        private static PopryzhenokEntities context;

        public static PopryzhenokEntities GetContext()
        {
            if (context == null)
                context = new PopryzhenokEntities();

            return context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgentCompany> AgentCompany { get; set; }
        public virtual DbSet<AgentType> AgentType { get; set; }
        public virtual DbSet<Annual_sale> Annual_sale { get; set; }
        public virtual DbSet<Director> Director { get; set; }
        public virtual DbSet<Implementation> Implementation { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
    }
}
